[GLOBAL]
pants_version = "2.18.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.build_files.fmt.black"
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true
resolves = {python-default = "python-default.lock"}

[python-bootstrap]
search_path = ["<PYENV>"]

[python-infer]
use_rust_parser = true

