python_sources(name="helper-library")

python_distribution(
    name="dist-helper-library",
    dependencies=[
        "//src/helper_library:helper-library",
    ],
    provides=setup_py(
        name="helper_library",
        version="1",
        description="Tiny little helper library.",
        author="Steffan",
        classifiers=[
            "Programming Language :: Python :: 3.9",
        ],
    ),
)
